# Generated by Django 6.1.1 on 2026-09-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_audit_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp', '-id'], 'verbose_name': 'entry record'},
        ),
    ]
